spring:
  application:
    name: vigorMotors

  datasource:
    url: jdbc:mysql://localhost:3306/vigorMotors
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9090
  