spring:
  application:
    name: vigorMotors

  datasource:
    url: jdbc:mysql://localhost:3306/vigorMotors
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9090

security:
  jwt:
    secret-key: u8AhznLPjTvgk9m6WRhvMx2fPQJjjg9rUCw+u0n08zA7FoxuVGEQIaNR0ULxIksTWuqUBKKW4+m3bzkwlI0eDA==
    token-expiration: 86400000